### ISSUE TITLE
linking `pocketfft` instead of `fftpack` for new Healpix

### ISSUE THREAD

**Issue by ntessore** [hsxavier/flask#4]
Healpix has replaced `fftpack` with `pocketfft` at some point (at least in the latest release 3.5.0). This requires a simple change from `-lfftpack` to `-lpocketfft` in the linker flags in flask's Makefile. Just putting it out here in case someone comes across the same issue.

**Comment by hsxavier** [comment]
Thanks for the feedback. I changed the Makefile to detect the Healpix
version and use the proper library.

**Comment by eddedmondson** [comment]
Had problems with the Makefile trying to use pocketfft rather than fftpack for Healpix 3.31 (splinter configuration). It's not clear to me why the Makefile would do that, certainly looks like it should work and detect the version as 3.31 and pick the right version.

I've put Healpix 3.50 in /share/splinter/cosmos/modules/may_2019/install_dir/Healpix_3.50/ anyway so we're not affected.

**Comment by hsxavier** [comment]
I believe this was fixed in commit 325074
